name: Auto-Tag Release
on:
 push:
   branches: [ main ]
permissions:
   contents: write
jobs:
 tag:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
    - uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
